# Generated by Django 2.2.1 on 2019-08-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('postal_code',), 'verbose_name_plural': 'Address'},
        ),
    ]
